// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kazjpebvshepisrbahqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthempwZWJ2c2hlcGlzcmJhaHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjcwNTUsImV4cCI6MjA3NjY0MzA1NX0.lCOWS13qLKNH_pR-PCBs7YnohEXFUpR7yIbUQHwJZto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});